<?php

/**
 * @file
 * Contains dorion_config.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function dorion_config_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the dorion_config module.
    case 'help.page.dorion_config':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('My Awesome Module') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function dorion_config_theme() {
  return [
    'dorion_config' => [
      'render element' => 'children',
    ],
  ];
}
