features:
  node_user_picture: true
  comment_user_picture: true
  comment_user_verification: true
  favicon: true
logo:
  use_default: true
  path: 'public://logo-100_1.png'
favicon:
  use_default: false
  path: 'public://bull-favicon.png'
  mimetype: image/png
